name: Script to curl apic

on: [pull_request, workflow_dispatch]
env:
  provider-org: 'michael'
  client-id: 599b7aef-8841-4ee2-88a0-84d49c4d6ff2
  client-secret: 0ea28423-e73b-47d4-b40e-ddb45c48bb0c
  api-host: platform-api.d-j02.apiconnect.dev.automation.ibm.com

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: curl apic to publish document
      run: |
        BODY='{"client_id":"${{ env.client-id }}","client_secret":"${{ env.client-secret }}","grant_type":"api_key","api_key":"${{ secrets.apicApikey }}","realm":"provider/default-idp-2"}'
        TOKEN=`curl -s -k -X "POST" -d $BODY -H "Accept: application/json" -H "Content-Type: application/json" https://${{ env.api-host}}/api/token | jq -r .access_token`
        #curl -v -k -X POST -H 'Accept: application/json' -H "Authorization: Bearer $TOKEN" https://${{ env.api-host}}/api/orgs/${{ env.provider-org }}/drafts/draft-apis?api_type=rest --data-binary @echo-api-inline.yaml -H 'Content-Type: application/yaml'
        curl -v -k -X POST -H 'Accept: application/json' -H "Authorization: Bearer $TOKEN" https://${{ env.api-host}}/api/orgs/${{ env.provider-org }}/drafts/draft-apis?api_type=rest -d "{\"draft_api\": `cat echo-api.json`}" -H 'Content-Type: application/json'

